name: deployment of portfolio

on:
  push:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: portfolio-v2/yarn.lock
      - name: enable corepack
        run: corepack enable
      - name: check yarn version
        run: yarn --version
      - name: install dependencies
        working-directory: portfolio-v2
        run: yarn install
      - name: build application
        working-directory: portfolio-v2
        run: yarn build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: portfolio-v2/dist/
      - name: test application
        working-directory: portfolio-v2
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: portfolio-v2/dist/
      - name: deploy application
        run: echo "application deployed successfully"

