name: deployment of portfolio

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: portfolio-v2/dist/
      - name: deploy application
        run: echo "application deployed successfully"

