name: deployment of portfolio

on:
  push:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: enable corepack
        run: corepack enable
      - name: activate yarn
        working-directory: portfolio-v2
        run: corepack prepare yarn@4.9.1 --activate
      - name: check version
        working-directory: portfolio-v2
        run: |
         yarn --version
         node --version
      - name: install dependencies
        working-directory: portfolio-v2
        run: yarn install
      - name: Test application
        working-directory: portfolio-v2
        run: yarn test
      - name: build application
        working-directory: portfolio-v2
        run: yarn build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: portfolio-v2/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: portfolio-v2/dist/
      - name: deploy application
        run: echo "application deployed successfully"

